### ISSUE TITLE
Data Groups

### ISSUE THREAD

**Issue by khdlr** [initze/thaw-slump-segmentation#43]
It would be nice to be able to define logical groups of datasets. For example, it would be much cleaner to have a config.yml that reads

```yml
  train:
    augment: true
    augment_types:
      - HorizontalFlip
      - VerticalFlip
      - Blur
      - RandomRotate90
      - RandomBrightnessContrast
      - MultiplicativeNoise
    shuffle: true
    scenes:
      - LenaDelta
      - Horton
      - BanksIsland
      - ...
```

instead of the current setup, where we have 100s of lines of cryptic scene ids in the config.
